2023-01-11 20:42:21,598 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 20:42:40,291 (INFO) - django.utils.autoreload - C:\Users\femto\Documents\femto\לקוחות\TreatNaturally\DjangoCleanCode\treatnaturallystore\treatnaturallystore\settings\dev.py changed, reloading.
2023-01-11 20:42:41,623 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 20:43:21,926 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 20:49:44,796 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 21:05:03,090 (INFO) - django.utils.autoreload - C:\Users\femto\Documents\femto\לקוחות\TreatNaturally\DjangoCleanCode\treatnaturallystore\store\models.py changed, reloading.
2023-01-11 21:05:04,231 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 21:06:37,496 (INFO) - django.utils.autoreload - C:\Users\femto\Documents\femto\לקוחות\TreatNaturally\DjangoCleanCode\treatnaturallystore\store\models.py changed, reloading.
2023-01-11 21:06:38,619 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 21:06:44,149 (INFO) - django.utils.autoreload - C:\Users\femto\Documents\femto\לקוחות\TreatNaturally\DjangoCleanCode\treatnaturallystore\store\models.py changed, reloading.
2023-01-11 21:06:45,339 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 21:07:55,543 (INFO) - django.utils.autoreload - C:\Users\femto\Documents\femto\לקוחות\TreatNaturally\DjangoCleanCode\treatnaturallystore\store\models.py changed, reloading.
2023-01-11 21:07:56,668 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 21:08:08,434 (INFO) - django.utils.autoreload - C:\Users\femto\Documents\femto\לקוחות\TreatNaturally\DjangoCleanCode\treatnaturallystore\store\models.py changed, reloading.
2023-01-11 21:08:09,691 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 21:31:07,492 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-11 21:31:07,535 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-11 21:31:10,247 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-11 21:32:14,315 (INFO) - django.utils.autoreload - C:\Users\femto\Documents\femto\לקוחות\TreatNaturally\DjangoCleanCode\treatnaturallystore\treatnaturallystore\urls.py changed, reloading.
2023-01-11 21:32:15,807 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-11 21:51:03,502 (INFO) - django.utils.autoreload - C:\Users\femto\.virtualenvs\treatnaturallystore-7dX3FTcm\Lib\site-packages\pkg_resources\_vendor\more_itertools\recipes.py changed, reloading.
2023-01-11 21:51:04,831 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 21:07:50,450 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 21:07:54,325 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:08:02,267 (WARNING) - django.request - Unauthorized: /auth/users/
2023-01-18 21:08:26,312 (WARNING) - django.request - Bad Request: /auth/users/
2023-01-18 21:08:26,609 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:08:26,861 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:08:38,251 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:08:38,458 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:09:25,700 (WARNING) - django.request - Method Not Allowed: /auth/jwt/createtoken
2023-01-18 21:09:25,981 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:10:13,073 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:10:13,250 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:10:30,367 (WARNING) - django.request - Method Not Allowed: /createtokens/
2023-01-18 21:10:43,747 (ERROR) - django.request - Internal Server Error: /createtokens/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework_simplejwt\views.py", line 27, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK\treatnaturallydev\core\serializers.py", line 32, in validate
    data.update({'membership': self.user.customer.membership })
                               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 463, in __get__
    raise self.RelatedObjectDoesNotExist(
core.models.User.customer.RelatedObjectDoesNotExist: User has no customer.
2023-01-18 21:10:44,162 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:10:44,353 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 21:17:22,008 (WARNING) - django.request - Forbidden: /store/customers/
2023-01-18 21:17:29,569 (ERROR) - django.request - Internal Server Error: /store/customers/me/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK\treatnaturallydev\store\views.py", line 100, in me
    customer = Customer.objects.get(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
store.models.Customer.DoesNotExist: Customer matching query does not exist.
2023-01-18 21:54:13,846 (INFO) - django.utils.autoreload - C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\pytz\lazy.py changed, reloading.
2023-01-18 21:54:17,768 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 21:54:21,477 (INFO) - django.utils.autoreload - C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\pkg_resources\_vendor\pyparsing\common.py changed, reloading.
2023-01-18 21:54:24,609 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 21:54:30,733 (INFO) - django.utils.autoreload - C:\Users\CB\.virtualenvs\treatnaturallydev-e_likyq6\Lib\site-packages\markupsafe\__init__.py changed, reloading.
2023-01-18 21:54:32,235 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 21:57:39,154 (WARNING) - django.request - Forbidden: /store/customers/
2023-01-18 21:58:47,328 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 22:03:29,650 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 22:05:08,166 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 22:05:08,659 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 22:07:36,792 (INFO) - django.utils.autoreload - D:\WORK\treatnaturallydev\store\apps.py changed, reloading.
2023-01-18 22:08:29,018 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-18 22:08:38,030 (WARNING) - django.request - Bad Request: /auth/users/
2023-01-18 22:08:50,319 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-18 22:08:50,562 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-19 16:48:37,732 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-19 16:48:44,765 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-19 16:49:03,702 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\urls.py changed, reloading.
2023-01-19 16:49:05,490 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-19 16:49:12,993 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\urls.py changed, reloading.
2023-01-19 16:49:16,170 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 20:54:54,932 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 20:55:05,424 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-22 20:56:34,383 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-22 20:56:35,296 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-22 20:56:37,822 (ERROR) - django.request - Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\sql\compiler.py", line 1385, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\sql\compiler.py", line 593, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
                                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\sql\compiler.py", line 71, in pre_sql_setup
    self.setup_query()
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\sql\compiler.py", line 62, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
                                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\sql\compiler.py", line 278, in get_select
    related_klass_infos = self.get_related_selections(select)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\db\models\sql\compiler.py", line 1193, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'tag'. Choices are: (none)
2023-01-22 20:56:39,477 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-22 20:57:01,653 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\admin.py changed, reloading.
2023-01-22 20:57:08,537 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 20:57:19,610 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-22 20:57:24,566 (WARNING) - django.request - Not Found: /favicon.ico
2023-01-22 20:59:59,118 (ERROR) - django.request - Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 309, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 284, in lookup_field
    value = attr()
            ^^^^^^
TypeError: create_reverse_many_to_one_manager.<locals>.RelatedManager.__call__() missing 1 required keyword-only argument: 'manager'
2023-01-22 21:01:34,678 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\models.py changed, reloading.
2023-01-22 21:01:43,032 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:02:03,098 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\admin.py changed, reloading.
2023-01-22 21:02:09,504 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:02:18,496 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\admin.py changed, reloading.
2023-01-22 21:02:26,287 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:02:34,302 (ERROR) - django.request - Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 309, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 284, in lookup_field
    value = attr()
            ^^^^^^
TypeError: create_reverse_many_to_one_manager.<locals>.RelatedManager.__call__() missing 1 required keyword-only argument: 'manager'
2023-01-22 21:03:17,974 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:03:37,724 (ERROR) - django.request - Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 309, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 284, in lookup_field
    value = attr()
            ^^^^^^
TypeError: create_reverse_many_to_one_manager.<locals>.RelatedManager.__call__() missing 1 required keyword-only argument: 'manager'
2023-01-22 21:05:53,499 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:06:01,835 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:06:10,288 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:06:16,286 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:06:22,664 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:06:28,921 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:06:35,679 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:06:42,099 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:06:49,025 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:06:55,287 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:07:03,018 (ERROR) - django.request - Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 309, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 284, in lookup_field
    value = attr()
            ^^^^^^
TypeError: create_reverse_many_to_one_manager.<locals>.RelatedManager.__call__() missing 1 required keyword-only argument: 'manager'
2023-01-22 21:07:45,773 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:07:52,074 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:08:05,893 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:08:13,402 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:08:20,699 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-22 21:08:28,646 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:09:54,508 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:10:23,725 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:10:29,274 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:10:35,132 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:10:42,763 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:11:31,874 (ERROR) - django.request - Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 309, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\contrib\admin\utils.py", line 284, in lookup_field
    value = attr()
            ^^^^^^
TypeError: create_reverse_many_to_one_manager.<locals>.RelatedManager.__call__() missing 1 required keyword-only argument: 'manager'
2023-01-22 21:18:57,481 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\admin.py changed, reloading.
2023-01-22 21:19:04,612 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:30:43,886 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\models.py changed, reloading.
2023-01-22 21:30:53,602 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:30:59,025 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\models.py changed, reloading.
2023-01-22 21:31:06,781 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:33:19,286 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:35:32,112 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:35:39,733 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:35:47,539 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:35:54,028 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:36:01,332 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:36:07,542 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:36:12,770 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:36:20,703 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:37:04,923 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:37:12,891 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:37:19,823 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:37:26,717 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:37:32,325 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:37:38,524 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:37:45,698 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:37:51,026 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:38:11,117 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:38:18,749 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:38:23,450 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:38:31,185 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:38:42,789 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:38:48,959 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:39:07,427 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:39:14,287 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:39:20,821 (ERROR) - django.request - Internal Server Error: /tags/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RelatedManager' object has no attribute 'tag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\relations.py", line 190, in get_attribute
    return super().get_attribute(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `tag` on serializer `TaggedItemSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `RelatedManager` instance.
Original exception text was: 'RelatedManager' object has no attribute 'tag'.
2023-01-22 21:40:10,391 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:40:16,085 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:40:20,718 (ERROR) - django.request - Internal Server Error: /tags/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `taggeditem` is not valid for model `TaggedItem`.
2023-01-22 21:40:40,480 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\models.py changed, reloading.
2023-01-22 21:41:17,062 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:41:21,517 (ERROR) - django.request - Internal Server Error: /tags/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tag' object has no attribute 'taggeditem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `taggeditem` on serializer `TagSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Tag` instance.
Original exception text was: 'Tag' object has no attribute 'taggeditem'.
2023-01-22 21:42:21,182 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:42:27,622 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:42:31,545 (ERROR) - django.request - Internal Server Error: /tags/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tag' object has no attribute 'taggeditems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `taggeditems` on serializer `TagSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Tag` instance.
Original exception text was: 'Tag' object has no attribute 'taggeditems'.
2023-01-22 21:42:31,579 (ERROR) - django.request - Internal Server Error: /tags/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tag' object has no attribute 'taggeditems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `taggeditems` on serializer `TagSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Tag` instance.
Original exception text was: 'Tag' object has no attribute 'taggeditems'.
2023-01-22 21:44:04,859 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\models.py changed, reloading.
2023-01-22 21:45:12,676 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:45:19,315 (ERROR) - django.request - Internal Server Error: /tags/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 357, in fields
    fields[key] = value
    ~~~~~~^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 169, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 367, in bind
    assert self.source != field_name, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: It is redundant to specify `source='taggeditems'` on field 'ListSerializer' in serializer 'TagSerializer', because it is the same as the field name. Remove the `source` keyword argument.
2023-01-22 21:45:34,480 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:45:40,049 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:45:44,305 (ERROR) - django.request - Internal Server Error: /tags/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\renderers.py", line 679, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BlogPost is not JSON serializable
2023-01-22 21:48:37,043 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:48:44,892 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:48:50,721 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:48:56,035 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:49:29,394 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:49:37,909 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:50:52,828 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:50:58,862 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:51:41,146 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:51:51,906 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:53:24,388 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:53:30,307 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:53:58,166 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:54:04,142 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:54:10,685 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:54:19,962 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:55:15,864 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:55:23,463 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:55:30,589 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\serializers.py changed, reloading.
2023-01-22 21:55:36,295 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:58:00,048 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:58:06,966 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:58:15,469 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:58:21,057 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:58:26,410 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:58:33,188 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:58:38,373 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:58:45,772 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:59:16,768 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:59:23,636 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:59:28,599 (ERROR) - django.request - Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `images` is not valid for model `BlogPost`.
2023-01-22 21:59:45,621 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 21:59:51,502 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 21:59:55,967 (ERROR) - django.request - Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `blogimages` is not valid for model `BlogPost`.
2023-01-22 22:01:09,776 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 22:01:16,381 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 22:01:35,864 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 22:01:42,277 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 22:01:48,347 (ERROR) - django.request - Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RelatedManager' object has no attribute 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB\.virtualenvs\treatnaturallydev-O5Fzlw50\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `image` on serializer `BlogPostImageSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `RelatedManager` instance.
Original exception text was: 'RelatedManager' object has no attribute 'image'.
2023-01-22 22:02:54,200 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\blog\serializers.py changed, reloading.
2023-01-22 22:02:59,719 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-22 22:03:36,332 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:57:50,123 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\treatnaturallystore\settings\common.py changed, reloading.
2023-01-23 19:57:52,196 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:58:09,752 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\treatnaturallystore\settings\common.py changed, reloading.
2023-01-23 19:58:11,289 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:58:46,543 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 19:58:49,344 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:58:55,867 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 19:58:57,211 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:59:25,653 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 19:59:27,140 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:59:30,658 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 19:59:32,023 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:59:36,259 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 19:59:39,129 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:59:43,134 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 19:59:44,470 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:59:47,971 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 19:59:49,228 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 19:59:59,000 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:00:00,458 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:00:02,388 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:00:06,043 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:00:18,448 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:00:19,807 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:00:25,624 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:00:28,444 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:00:31,480 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:00:34,465 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:00:41,241 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:00:42,753 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:00:46,996 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:00:48,438 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:01:01,447 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\models.py changed, reloading.
2023-01-23 20:01:02,891 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:06:04,291 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\urls.py changed, reloading.
2023-01-23 20:06:07,735 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:06:28,405 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\treatnaturallystore\urls.py changed, reloading.
2023-01-23 20:06:32,003 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:06:39,641 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\treatnaturallystore\urls.py changed, reloading.
2023-01-23 20:06:43,061 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:08:36,176 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\views.py changed, reloading.
2023-01-23 20:08:39,245 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:09:40,771 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\admin.py changed, reloading.
2023-01-23 20:09:42,239 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:09:44,910 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\admin.py changed, reloading.
2023-01-23 20:09:48,121 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:09:53,673 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\admin.py changed, reloading.
2023-01-23 20:09:56,544 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:10:01,911 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\admin.py changed, reloading.
2023-01-23 20:10:04,997 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:10:10,010 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\ailments\admin.py changed, reloading.
2023-01-23 20:10:13,102 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:11:00,185 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:11:01,656 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:11:05,651 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:11:08,912 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:11:16,040 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:11:17,554 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:11:22,761 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:11:25,674 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:11:34,435 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:11:35,765 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:11:38,310 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:11:39,624 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:11:58,142 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:11:59,510 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:07,145 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:08,743 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:10,937 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:13,464 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:15,575 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:18,200 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:28,796 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:30,220 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:32,819 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:34,200 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:41,727 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:44,835 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:47,541 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:50,324 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:12:53,713 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:12:56,471 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:13:01,889 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:13:03,471 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:13:07,759 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:13:09,125 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:13:11,685 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\core\admin.py changed, reloading.
2023-01-23 20:13:14,837 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:36:19,252 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\store\models.py changed, reloading.
2023-01-23 20:36:22,165 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:36:26,268 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\store\models.py changed, reloading.
2023-01-23 20:36:27,685 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:57:51,775 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\views.py changed, reloading.
2023-01-23 20:57:55,369 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:58:02,455 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\views.py changed, reloading.
2023-01-23 20:58:03,932 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-01-23 20:58:34,615 (INFO) - django.utils.autoreload - D:\WORK\TreatNaturally\treatnaturallydev\tags\views.py changed, reloading.
2023-01-23 20:58:37,766 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
